### ISSUE TITLE
0.19 Checklist

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#187]
This is for my reference when it's time to upgrade stuff for 0.19. 😄 

- [ ] Instead of using `Native`, slice in a `rtfeldman$node_test_runner$runThunk = // runThunk implementation goes here` at the end of `elmTestOutput.js` to overwrite the generated definition. Do that [right here](https://github.com/rtfeldman/node-test-runner/blob/5fa25a6849c83eee4acb22453e596bbfd274a295/lib/elm-test.js#L240-L241).
- [ ] Instead of symlinking to `elm-stuff`, symlink `elm-stuff/build-artifacts` and `elm-stuff/dependencies` separately - otherwise we'll get a recursive symlink on `elm-stuff`
- [ ] Don't have a separate `elm-package.json` or test dir for tests; instead, use `test-dependencies` and the root project's `elm-stuff` for everything.
- [ ] Replace `add-dependencies` with `elm-test install` to add stuff to `test-dependencies`
- [ ] Update `elm-test init`
