### ISSUE TITLE
checklist of stuff left over from #257 upgrade to Elm 0.19 

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#268]
## TODO (between rc release and stable release)
  - [x] Make sure formatting of `String.join ","` places are okay
  - [x] restore the "(Elm 0.19 beta allows multiple ports with the same name?)" test after that gets fixed in Elm https://elmlang.slack.com/archives/C13L7S5GR/p1528239699000411
  - [x] restore `.travis.yml` after official Elm binaries are published
  - [x] error message "No tests found in the test/ (or tests/) directory." should only allow "tests"
  - [x] remove binstall dependency after updating to elmi-to-json-0.19.0-rc4

**Comment by andys8** [comment]
And update example in `README` and remove cpu number workaround if possible.

**Comment by rtfeldman** [comment]
These are all done now!
