### ISSUE TITLE
 0.19.1-revision8 Changelog

### ISSUE THREAD

**Issue by harrysarson** [rtfeldman/node-test-runner#560]
- [ ] Note dropping support for node 10 #559
- [ ] Make it easy for people to try the new Fuzz stuff #592
- [ ] Use elm-solve-deps-wasm instead of elm-json solve #558 
- [ ] Fix parsing of char literals with unicode escapes #594 
- [ ] Now shows suggestions on misspelled CLI flags (thanks to Commander update in https://github.com/rtfeldman/node-test-runner/pull/603)
